import { renderIcon } from '@/utils';
import {
  DashboardOutlined,
  NotificationOutlined,
  NotificationTwotone,
  InfoOutlined,
  NotificationFilled,
  EditFilled,
  AccountBookFilled,
  AccountBookOutlined,
  AccountBookTwotone,
  AimOutlined,
  AlertFilled,
  AlertOutlined,
  AlertTwotone,
  AlibabaOutlined,
  AlignCenterOutlined,
  AlignLeftOutlined,
  AlignRightOutlined,
  AlipayOutlined,
  AlipayCircleFilled,
  AliwangwangFilled,
  AliwangwangOutlined,
  AliyunOutlined,
  AlipayCircleOutlined,
  AmazonOutlined,
  AlipaySquareFilled,
  AndroidFilled,
  AndroidOutlined
} from '@vicons/antd';
import {RouterIcon} from "@/router/types";

//前端路由图标映射表
export const constantRouterIcon:RouterIcon = {
  DashboardOutlined: {icon: renderIcon(DashboardOutlined), name: 'DashboardOutlined'},
  NotificationOutlined: {icon: renderIcon(NotificationOutlined), name: 'NotificationOutlined'},
  NotificationTwotone: {icon: renderIcon(NotificationTwotone), name: 'NotificationTwotone'},
  InfoOutlined: {icon: renderIcon(InfoOutlined), name: 'InfoOutlined'},
  NotificationFilled: {icon: renderIcon(NotificationFilled), name: 'NotificationFilled'},
  EditFilled: {icon: renderIcon(EditFilled), name: 'EditFilled'},
  AccountBookFilled: {icon: renderIcon(AccountBookFilled), name: 'AccountBookFilled'},
  AccountBookOutlined: {icon: renderIcon(AccountBookOutlined), name: 'AccountBookOutlined'},
  AccountBookTwotone: {icon: renderIcon(AccountBookTwotone), name: 'AccountBookTwotone'},
  AimOutlined: {icon: renderIcon(AimOutlined), name: 'AimOutlined'},
  AlertFilled: {icon: renderIcon(AlertFilled), name: 'AlertFilled'},
  AlertOutlined: {icon: renderIcon(AlertOutlined), name: 'AlertOutlined'},
  AlertTwotone: {icon: renderIcon(AlertTwotone), name: 'AlertTwotone'},
  AlibabaOutlined: {icon: renderIcon(AlibabaOutlined), name: 'AlibabaOutlined'},
  AlignCenterOutlined: {icon: renderIcon(AlignCenterOutlined), name: 'AlignCenterOutlined'},
  AlignLeftOutlined: {icon: renderIcon(AlignLeftOutlined), name: 'AlignLeftOutlined'},
  AlignRightOutlined: {icon: renderIcon(AlignRightOutlined), name: 'AlignRightOutlined'},
  AlipayOutlined: {icon: renderIcon(AlipayOutlined), name: 'AlipayOutlined'},
  AlipayCircleFilled: {icon: renderIcon(AlipayCircleFilled), name: 'AlipayCircleFilled'},
  AliwangwangFilled: {icon: renderIcon(AliwangwangFilled), name: 'AliwangwangFilled'},
  AliwangwangOutlined: {icon: renderIcon(AliwangwangOutlined), name: 'AliwangwangOutlined'},
  AliyunOutlined: {icon: renderIcon(AliyunOutlined), name: 'AliyunOutlined'},
  AlipayCircleOutlined: {icon: renderIcon(AlipayCircleOutlined), name: 'AlipayCircleOutlined'},
  AmazonOutlined: {icon: renderIcon(AmazonOutlined), name: 'AmazonOutlined'},
  AlipaySquareFilled: {icon: renderIcon(AlipaySquareFilled), name: 'AlipaySquareFilled'},
  AndroidFilled: {icon: renderIcon(AndroidFilled), name: 'AndroidFilled'},
  AndroidOutlined: {icon: renderIcon(AndroidOutlined), name: 'AndroidOutlined'},
}
