server:
  port: 9190
spring:
  application:
    name: deharvesting-informatization
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://47.100.250.1:3306/deharvesting-informatization?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai
      username: root
      password: bJF@010822
      driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:      # 密码（默认为空）
    timeout: 6000ms  # 连接超时时长（毫秒）
    lettuce:
      pool:
        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: 10000ms      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 5       # 连接池中的最小空闲连接
mybatis-plus:
  mapper-locations: classpath:com/cby/tcs/**/mapper/*.xml
  type-aliases-package: com.cby.**.entity
  global-config:
    banner: false
    db-config:
      id-type: ASSIGN_UUID
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印SQL语句
sa-token:
  # 是否打印logo
  is-print: false
  # token 名称（同时也是 cookie 名称）
  token-name: access_token
  # token 风格
  token-style: tik
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: 2592000
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  active-timeout: -1
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: false
  # 是否输出操作日志
  is-log: true
  # jwt秘钥
  jwt-secret-key: deharvesting_informatization
app:
  config:
    exclude-path:
      - /user/login
      - /user/register
      - /user/validAccount
      - /user/getLoginVerifyImg
      - /message/pull
